events {}

http {
    upstream coletor_cluster {
        server coletor1:8080;
        server coletor2:8080;
        server coletor3:8080;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://coletor_cluster;
        }
    }
}
